# Generated by Django 3.0.8 on 2020-07-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('university', models.CharField(choices=[('USTHB', 'USTHB'), ('ENP', 'ENP'), ('ENSTP', 'ENSTP'), ('ESI', 'ESI'), ('ESSA', 'ESSA'), ('O', 'Other')], max_length=5)),
                ('branch', models.CharField(choices=[('MI', 'Mathematique et Informatique'), ('SM', 'Science de la Matière'), ('ST', 'Science et Technologie'), ('SNV', 'Science de la Nature et de la Vie'), ('STU', "Science de la Terre et de l'Univers"), ('Mathematique', 'Mathematique'), ('FEI', 'Electronique et Informatique'), ('Physique', 'Physique'), ('Chimie', 'Chimie'), ('GC', 'Génie Civile'), ('GM', 'Génie Mecanique'), ('GP', 'Génie des Procédés'), ('Bio', 'Biologie'), ('Science de la Terre', 'Science de la Terre'), ('GAT', 'Géographie et Amenagement du Territoire'), ('O', 'Other')], max_length=20)),
                ('level', models.CharField(choices=[('L1', 'License 1'), ('L2', 'License 2'), ('L3', 'License 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D', 'Doctorat'), ('O', 'Other')], max_length=5)),
                ('availability', models.BooleanField()),
                ('experience', models.BooleanField()),
                ('do_git', models.BooleanField()),
                ('do_fest', models.BooleanField()),
                ('conduct', models.BooleanField()),
            ],
        ),
    ]
