# Generated by Django 3.0.8 on 2020-07-25 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='availability',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, error_messages={'required': 'Please check one of the options to proceed'}),
        ),
        migrations.AlterField(
            model_name='participant',
            name='conduct',
            field=models.BooleanField(error_messages={'required': 'Please read Code of Conduct to proceed'}),
        ),
        migrations.AlterField(
            model_name='participant',
            name='do_fest',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, error_messages={'required': 'Please check one of the options to proceed'}),
        ),
        migrations.AlterField(
            model_name='participant',
            name='do_git',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, error_messages={'required': 'Please check one of the options to proceed'}),
        ),
        migrations.AlterField(
            model_name='participant',
            name='experience',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, error_messages={'required': 'Please check one of the options to proceed'}),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_first_name', message='This is not a valid First Name', regex="^[a-zA-Z]+(([\\'\\,\\.\\- ][a-zA-Z ])?[a-zA-Z]*)*$")]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_last_name', message='This is not a valid Last Name', regex="^[a-zA-Z]+(([\\'\\,\\.\\- ][a-zA-Z ])?[a-zA-Z]*)*$")]),
        ),
    ]
