# Generated by Django 3.0.8 on 2020-07-25 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_auto_20200726_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='availability',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, error_messages={'required': 'Please check either option to proceed.'}),
        ),
        migrations.AlterField(
            model_name='participant',
            name='branch',
            field=models.CharField(choices=[('MI', 'Mathematique et Informatique'), ('SM', 'Science de la Matière'), ('ST', 'Science et Technologie'), ('SNV', 'Science de la Nature et de la Vie'), ('STU', "Science de la Terre et de l'Univers"), ('Mathematique', 'Mathematique'), ('FEI', 'Electronique et Informatique'), ('Physique', 'Physique'), ('Chimie', 'Chimie'), ('GC', 'Génie Civile'), ('GM', 'Génie Mecanique'), ('GP', 'Génie des Procédés'), ('Bio', 'Biologie'), ('Science de la Terre', 'Science de la Terre'), ('GAT', 'Géographie et Amenagement du Territoire'), ('O', 'Other')], error_messages={'required': 'Please select your branch.'}, max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='conduct',
            field=models.BooleanField(error_messages={'required': 'Please read Code of Conduct to proceed.'}),
        ),
        migrations.AlterField(
            model_name='participant',
            name='do_fest',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, error_messages={'required': 'Please check either option to proceed.'}),
        ),
        migrations.AlterField(
            model_name='participant',
            name='do_git',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, error_messages={'required': 'Please check either option to proceed.'}),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(error_messages={'required': 'Please fill in your email.'}, max_length=254),
        ),
        migrations.AlterField(
            model_name='participant',
            name='experience',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, error_messages={'required': 'Please check either option to proceed.'}),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(error_messages={'required': 'Please fill in your first name.'}, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_first_name', message='This is not a valid first name.', regex="^[a-zA-Z]+(([\\'\\,\\.\\- ][a-zA-Z ])?[a-zA-Z]*)*$")]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(error_messages={'required': 'Please fill in your last name.'}, max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_last_name', message='This is not a valid last name.', regex="^[a-zA-Z]+(([\\'\\,\\.\\- ][a-zA-Z ])?[a-zA-Z]*)*$")]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='level',
            field=models.CharField(choices=[('L1', 'License 1'), ('L2', 'License 2'), ('L3', 'License 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D', 'Doctorat'), ('O', 'Other')], error_messages={'required': 'Please select your level.'}, max_length=5),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.IntegerField(error_messages={'required': 'Please fill in your phone number.'}),
        ),
        migrations.AlterField(
            model_name='participant',
            name='university',
            field=models.CharField(choices=[('USTHB', 'USTHB'), ('ENP', 'ENP'), ('ENSTP', 'ENSTP'), ('ESI', 'ESI'), ('ESSA', 'ESSA'), ('O', 'Other')], error_messages={'required': 'Please select your university.'}, max_length=5),
        ),
    ]
