# Generated by Django 3.0.8 on 2020-07-25 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_auto_20200726_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'Please fill in your first name.'}, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_first_name', message='This is not a valid first name.', regex="^[a-zA-Z]+(([\\'\\,\\.\\- ][a-zA-Z ])?[a-zA-Z]*)*$")]),
        ),
    ]
