# Generated by Django 3.0.8 on 2020-07-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0005_auto_20200726_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='availability',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='conduct',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='do_fest',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='do_git',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='experience',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
