# Generated by Django 3.0.8 on 2020-07-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0007_auto_20200726_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='university',
            field=models.CharField(choices=[('', 'Select Your University'), ('USTHB', 'USTHB'), ('ENP', 'ENP'), ('ENSTP', 'ENSTP'), ('ESI', 'ESI'), ('ESSA', 'ESSA'), ('O', 'Other')], max_length=5),
        ),
    ]
