# Generated by Django 3.0.8 on 2020-07-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0009_auto_20200726_0218'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique name'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('email',), name='unique email'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='unique phone_number'),
        ),
    ]
