# Generated by Django 3.0.8 on 2020-07-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0012_auto_20200726_0314'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participant',
            name='unique email',
        ),
        migrations.RemoveConstraint(
            model_name='participant',
            name='unique phone_number',
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique user name'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('email',), name='unique user email'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='unique user phone number'),
        ),
    ]
