# Generated by Django 3.0.8 on 2020-07-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0013_auto_20200726_2008'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participant',
            name='unique user name',
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('first_name', 'last_name')},
        ),
    ]
