# Generated by Django 3.0.8 on 2020-07-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0014_auto_20200726_2314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
    ]
