# Generated by Django 3.0.8 on 2020-07-26 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0015_auto_20200726_2315'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participant',
            name='unique user email',
        ),
        migrations.RemoveConstraint(
            model_name='participant',
            name='unique user phone number',
        ),
    ]
