# Generated by Django 3.0.8 on 2020-07-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0017_auto_20200726_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='conduct',
        ),
    ]
