# Generated by Django 3.0.8 on 2020-07-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0018_remove_participant_conduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='conduct',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
