# Generated by Django 3.0.8 on 2020-07-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0019_participant_conduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='id',
        ),
        migrations.AlterField(
            model_name='participant',
            name='availability',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='do_fest',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='do_git',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='experience',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')]),
        ),
    ]
