# Generated by Django 3.0.8 on 2020-07-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0020_auto_20200727_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='availability',
            field=models.BooleanField(choices=[('', ''), (1, 'Yes'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='do_fest',
            field=models.BooleanField(choices=[('', ''), (1, 'Yes'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='do_git',
            field=models.BooleanField(choices=[('', ''), (1, 'Yes'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='experience',
            field=models.BooleanField(choices=[('', ''), (1, 'Yes'), (0, 'No')]),
        ),
    ]
