# Generated by Django 3.0.8 on 2020-07-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0021_auto_20200727_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='availability',
            field=models.BooleanField(choices=[('', 'Select Option'), (1, 'Yes'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='do_fest',
            field=models.BooleanField(choices=[('', 'Select Option'), (1, 'Yes'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='do_git',
            field=models.BooleanField(choices=[('', 'Select Option'), (1, 'Yes'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='experience',
            field=models.BooleanField(choices=[('', 'Select Option'), (1, 'Yes'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='level',
            field=models.CharField(choices=[('', 'Select Your Level'), ('L1', 'Undergrad. deg. 1'), ('L2', 'Undergrad. deg. 2'), ('L3', 'Undergrad. deg. 3'), ('M1', "Master's deg. 1"), ('M2', "Master's deg. 2"), ('D', 'Doctorate deg.'), ('O', 'Other')], max_length=5),
        ),
    ]
